name: pasty-test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  pasty-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout rpetit3/pasty
        uses: actions/checkout@v2

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pasty
          auto-activate-base: false

      - name: Setup pasty Environment
        run: |
          conda install -y -c conda-forge -c bioconda rich-click executor 'python>=3.7' blast

      - name: Environment Information
        run: uname -a && env

      - name: Test pasty basics
        run: |
          echo "Testing patsy"
          bin/pasty --version
          bin/pasty --help

      - name: Test patsy
        run: |
          echo "O1-GCA_000705235"
          bin/pasty --assembly test/O1-GCA_000705235.fna.gz --prefix O1-GCA_000705235 --db db/OSAdb.fasta
          cat O1-GCA_000705235.tsv
          cat O1-GCA_000705235.details.tsv
          echo "O2-GCF_000006765"
          bin/pasty --assembly test/O2-GCF_000006765.fna.gz --prefix O2-GCF_000006765 --outdir O2
          cat O2/O2-GCF_000006765.tsv
          cat O2/O2-GCF_000006765.details.tsv
          echo "O6-GCF_001457615"
          bin/pasty --assembly test/O6-GCF_001457615.fna.gz --prefix O6-GCF_001457615
          cat O6-GCF_001457615.tsv
          cat O6-GCF_001457615.details.tsv
          echo "O7-GCF_000647615"
          bin/pasty --assembly test/O7-GCF_000647615.fna.gz --prefix O7-GCF_000647615
          cat O7-GCF_000647615.tsv
          cat O7-GCF_000647615.details.tsv
          echo "NT-GCF_000292685"
          bin/pasty --assembly test/NT-GCF_000292685.fna.gz --prefix NT-GCF_000292685 --db db/OSAdb.fasta
          cat NT-GCF_000292685.tsv
          cat NT-GCF_000292685.details.tsv
          echo "empty"
          bin/pasty --assembly test/empty.fasta --prefix empty
          cat empty.tsv
          cat empty.details.tsv
          echo "not-a-fasta"
          bin/pasty --assembly test/not-a-fasta.fasta --prefix not-a-fasta
          cat not-a-fasta.tsv
          cat not-a-fasta.details.tsv
          echo "poor"
          bin/pasty --assembly test/poor.fasta --prefix poor --outdir poor
          cat poor/poor.tsv
          cat poor/poor.details.tsv
