name: pasty-test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  pasty-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout rpetit3/pasty
        uses: actions/checkout@v2

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pasty
          auto-activate-base: false

      - name: Setup pasty Environment
        run: |
          conda install -y -c conda-forge -c bioconda rich-click executor 'python>=3.7' blast

      - name: Environment Information
        run: uname -a && env

      - name: Test pasty basics
        run: |
          echo "Testing patsy"
          bin/pasty --version
          bin/pasty --help

      - name: Test patsy
        run: |
          echo "O1-GCF_000504045"
          bin/pasty --assembly test/O1-GCF_000504045.fna.gz --prefix O1-GCF_000504045 --db db/OSAdb.fasta
          cat O1-GCF_000504045.tsv
          cat O1-GCF_000504045.details.tsv
          echo "O2-GCF_000006765"
          bin/pasty --assembly test/O2-GCF_000006765.fna.gz --prefix O2-GCF_000006765 --outdir O2
          cat O2/O2-GCF_000006765.tsv
          cat O2/O2-GCF_000006765.details.tsv
          echo "O3-GCF_000271365"
          bin/pasty --assembly test/O3-GCF_000271365.fna.gz --prefix O3-GCF_000271365 --outdir O3
          cat O3/O3-GCF_000271365.tsv
          cat O3/O3-GCF_000271365.details.tsv
          echo "O4-GCF_024652945"
          bin/pasty --assembly test/O4-GCF_024652945.fna.gz --prefix O4-GCF_024652945 --outdir O4
          cat O4/O4-GCF_024652945.tsv
          cat O4/O4-GCF_024652945.details.tsv
          echo "O6-GCF_001457615"
          bin/pasty --assembly test/O6-GCF_001457615.fna.gz --prefix O6-GCF_001457615
          cat O6-GCF_001457615.tsv
          cat O6-GCF_001457615.details.tsv
          echo "O7-GCF_000647615"
          bin/pasty --assembly test/O7-GCF_000647615.fna.gz --prefix O7-GCF_000647615
          cat O7-GCF_000647615.tsv
          cat O7-GCF_000647615.details.tsv
          echo "O9-GCF_002075065"
          bin/pasty --assembly test/O9-GCF_002075065.fna.gz --prefix O9-GCF_002075065
          cat O9-GCF_002075065.tsv
          cat O9-GCF_002075065.details.tsv
          echo "O10-GCF_009676765"
          bin/pasty --assembly test/O10-GCF_009676765.fna.gz --prefix O10-GCF_009676765
          cat O10-GCF_009676765.tsv
          cat O10-GCF_009676765.details.tsv
          echo "O11-GCF_002192495"
          bin/pasty --assembly test/O11-GCF_002192495.fna.gz --prefix O11-GCF_002192495
          cat O11-GCF_002192495.tsv
          cat O11-GCF_002192495.details.tsv
          echo "O12-GCF_000981825"
          bin/pasty --assembly test/O12-GCF_000981825.fna.gz --prefix O12-GCF_000981825
          cat O12-GCF_000981825.tsv
          cat O12-GCF_000981825.details.tsv
          echo "NT-GCF_000292685"
          bin/pasty --assembly test/NT-GCF_000292685.fna.gz --prefix NT-GCF_000292685 --db db/OSAdb.fasta
          cat NT-GCF_000292685.tsv
          cat NT-GCF_000292685.details.tsv
          echo "empty"
          bin/pasty --assembly test/empty.fasta --prefix empty
          cat empty.tsv
          cat empty.details.tsv
          echo "not-a-fasta"
          bin/pasty --assembly test/not-a-fasta.fasta --prefix not-a-fasta
          cat not-a-fasta.tsv
          cat not-a-fasta.details.tsv
          echo "poor"
          bin/pasty --assembly test/poor.fasta --prefix poor --outdir poor
          cat poor/poor.tsv
          cat poor/poor.details.tsv
